;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Abilities.DealDamage.Melee",NewTagName="Abilities.Attack.Melee")
+GameplayTagRedirects=(OldTagName="Abilities.DealDamage",NewTagName="Abilities.Attack")
+GameplayTagRedirects=(OldTagName="GameplayCue.Damage.Take",NewTagName="GameplayCue.Damage.Received")
+GameplayTagList=(Tag="Abilities.ApplyImpulse",DevComment="")
+GameplayTagList=(Tag="Abilities.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Abilities.Attack.Sword",DevComment="")
+GameplayTagList=(Tag="Abilities.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldown.ApplyImpulse",DevComment="")
+GameplayTagList=(Tag="Cooldown.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Event.Attack",DevComment="")
+GameplayTagList=(Tag="Event.Dash",DevComment="")
+GameplayTagList=(Tag="Event.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Attack.Sword.Slash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Player",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")

